export const noTranslationsError = `No updates found! Are you sure you're running this command in the right directory?`;
export const noLocalesError = `No locales found! Please provide a list of locales to translate to, or specify them in your gt.config.json file.`;
export const noDefaultLocaleError = `No default locale found! Please provide a default locale, or specify it in your gt.config.json file.`;
export const noTranslationsDirError = `No translations directory found! Please provide a path to the directory where translations will be saved, or specify it in your gt.config.json file.`;
export const noSourceFileError = `No source file found! Please double check your translations directory and default locale.`;
export const noDataFormatError = `No data format found! Please make sure your translationsDir parameter ends with a supported file extension.`;
export const noSupportedDataFormatError = `Unsupported data format! Please make sure your translationsDir parameter ends with a supported file extension.`;
export const noApiKeyError = `No API key found! Please provide an API key using the --api-key flag.`;
export const noProjectIdError = `No project ID found! Please provide a project ID using the --project-id flag or specify it in your gt.config.json file.`;
