import { GTProvider } from './provider/GTProvider';
import LocaleSelector from './ui/LocaleSelector';
import RegionSelector from './ui/RegionSelector';

import {
  T,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useRegion,
  Var,
  Num,
  Currency,
  DateTime,
  Plural,
  Branch,
  useLocales,
  useLocaleSelector,
  useSetLocale,
  useGTClass,
  useLocaleProperties,
  useRegionSelector,
  useLocaleDirection,
  useMessages,
  msg,
  decodeMsg,
  decodeOptions,
} from '@generaltranslation/react-core';
import {
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
} from '@generaltranslation/react-core/types';
import { getLocale } from './utils/getLocale';

export {
  getLocale,
  Var,
  Num,
  Currency,
  DateTime,
  T,
  GTProvider,
  Plural,
  Branch,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useLocales,
  useSetLocale,
  useLocaleSelector,
  useRegion,
  useRegionSelector,
  useGTClass,
  useLocaleProperties,
  useLocaleDirection,
  LocaleSelector,
  RegionSelector,
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
  msg,
  decodeMsg,
  decodeOptions,
  useMessages,
};
