packages:
  - packages/*
  - test-apps/**/*
  - examples/next-ssg

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@generaltranslation/*'
  - gt-next
  - gt-react
  - gt-sanity
  - gt-i18n
  - gtx-cli
  - generaltranslation
  - next
  - '@next/*'
  - 'react'
  - 'react-dom'

overrides:
  '@generaltranslation/next-internal': link:packages/next-internal
