packages:
  - packages/*
  - tests/apps/**/*
  - examples/*

enableGlobalVirtualStore: true
hoist: false

onlyBuiltDependencies:
  - lefthook

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@generaltranslation/*'
  - gt-next
  - gt-react
  - gt-sanity
  - '@generaltranslation/format'
  - gt-i18n
  - gt
  - gtx-cli
  - generaltranslation
  - next
  - '@next/*'
  - gt-react-native
  - 'react'
  - 'react-dom'

catalog:
  '@babel/core': ^7.28.4
  '@typescript/native': npm:typescript@^7.0.2
  '@types/node': ^22.13.5
  oxfmt: ^0.47.0
  oxlint: ^1.62.0
  tsdown: 0.22.12
  tslib: ^2.8.1
  typescript: npm:@typescript/typescript6@^6.0.2
  vitest: ^3.2.4

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      next: '*'
  '@expo/cli@*':
    dependencies:
      metro-runtime: '*'
  size-limit@*:
    dependencies:
      '@size-limit/preset-small-lib': '*'
