// Helpers for recognising the `sanity-plugin-internationalized-array` storage
// shape, where a localized field is stored as an array of per-locale items:
//
//   title: [
//     { _key: 'abc', _type: 'internationalizedArrayStringValue', language: 'en', value: 'Hello' },
//     { _key: 'def', _type: 'internationalizedArrayStringValue', language: 'es', value: 'Hola' },
//   ]
//
// Detection is shape-based (not config-based) so the serializer/merger do not
// have to read plugin config or thread the schema through every call.

export const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

export type InternationalizedArrayItem = {
  _key?: string;
  _type: string;
  language: string;
  value: unknown;
};

/**
 * A single `{ _key, _type, language, value }` entry. The `_type` of the value
 * objects generated by the reference plugin always ends in `Value`
 * (e.g. `internationalizedArrayStringValue`).
 */
export function isInternationalizedArrayItem(
  item: unknown
): item is InternationalizedArrayItem {
  return (
    isRecord(item) &&
    typeof item._type === 'string' &&
    item._type.endsWith('Value') &&
    typeof item.language === 'string' &&
    'value' in item
  );
}

/**
 * A non-empty array where every element is an internationalized-array item.
 */
export function isInternationalizedArrayField(
  value: unknown
): value is InternationalizedArrayItem[] {
  return (
    Array.isArray(value) &&
    value.length > 0 &&
    value.every(isInternationalizedArrayItem)
  );
}

/**
 * Returns the item for a given locale, matching on the exact `language` id
 * (hyphens preserved, e.g. `fr-CA`). Never matches on `_key`, which is random.
 */
export function findLocaleItem(
  field: InternationalizedArrayItem[],
  locale: string
): InternationalizedArrayItem | undefined {
  return field.find((item) => item.language === locale);
}
