import fs from 'node:fs';
import path from 'node:path';
import { logError } from '../../console/logging.js';

/**
 * Creates a loadTranslations.js file for Expo projects using local translations
 * This file is imported by the GTProvider to load translation files at runtime
 * Reads locales from gt.config.json and generates require statements
 */
export async function createLoadTranslationsFile(
  projectRoot: string,
  errors: string[],
  warnings: string[],
  filesUpdated: string[],
  providedLocales?: string[],
  providedDefaultLocale?: string
): Promise<void> {
  try {
    const filePath = path.join(projectRoot, 'loadTranslations.js');

    // Skip if file already exists
    if (fs.existsSync(filePath)) {
      return;
    }

    // Use provided locales or read from gt.config.json
    let locales: string[] = providedLocales || [];
    let defaultLocale: string = providedDefaultLocale || 'en';

    if (!providedLocales) {
      // Read gt.config.json to get locales and default locale
      const gtConfigPath = path.resolve(projectRoot, 'gt.config.json');
      if (fs.existsSync(gtConfigPath)) {
        try {
          const gtConfig = JSON.parse(fs.readFileSync(gtConfigPath, 'utf-8'));
          if (gtConfig.locales && Array.isArray(gtConfig.locales)) {
            locales = gtConfig.locales;
          }
          if (gtConfig.defaultLocale) {
            defaultLocale = gtConfig.defaultLocale;
          }
        } catch (error) {
          warnings.push(
            `Failed to read gt.config.json, using default locale: ${defaultLocale}`
          );
        }
      }
    }

    // Filter out the default locale - only include other locales
    const nonDefaultLocales = locales.filter(
      (locale) => locale !== defaultLocale
    );

    // Generate require statements for non-default locales
    const requireStatements = nonDefaultLocales
      .map((locale) => `  ${locale}: require('./translations/${locale}.json'),`)
      .join('\n');

    const loadTranslationsContent = `// Add additional locales here as they are generated by GT
const translations = {
${requireStatements}
};

export default async function loadTranslations(locale) {
  try {
    // Return the translation object for the requested locale
    const t = translations[locale];
    if (!t) {
      console.warn(
        \`No translations found for locale \${locale}, falling back to empty object\`
      );
      return {};
    }
    return t;
  } catch (error) {
    console.warn(\`Failed to load translations for locale \${locale}:\`, error);
    return {};
  }
}
`;

    fs.writeFileSync(filePath, loadTranslationsContent);
    filesUpdated.push(filePath);
  } catch (error) {
    logError(`Error creating loadTranslations.js: ${error}`);
    errors.push(`Failed to create loadTranslations.js: ${error}`);
  }
}
