import type { Example } from '../types';

/**
 * Focused probes outside the larger expression/component matrices: the exact
 * ECMAScript whitespace set and entity decoding, raw line endings, evaluation
 * order around keys/spreads/children, lexical bindings, and existing wrappers.
 * Expected files are always generated by the real compiler insertion pass.
 */
function example(name: string, input: string): Example {
  return { name: `adversarial/${name}`, input };
}

function page(name: string, body: string, imports = ''): Example {
  return example(name, `${imports}\nexport const Page = () => (${body});\n`);
}

const candidates: Example[] = [];

// Entity text must be classified after JSX decoding, including whitespace-only
// entities and named bidi controls that are not JavaScript whitespace.
for (const [name, content] of [
  ['copyright', '&copy;'],
  ['registered', '&reg;'],
  ['trade-mark', '&trade;'],
  ['emdash', '&mdash;'],
  ['ellipsis', '&hellip;'],
  ['eacute', '&eacute;'],
  ['greek', '&Alpha;&omega;'],
  ['math', '&sum;&ne;&infin;'],
  ['nbsp', '&nbsp;'],
  ['ensp', '&ensp;'],
  ['emsp', '&emsp;'],
  ['thinsp', '&thinsp;'],
  ['zwnj', '&zwnj;'],
  ['zwj', '&zwj;'],
  ['lrm', '&lrm;'],
  ['rlm', '&rlm;'],
  ['numeric-bom', '&#65279;'],
  ['hex-bom', '&#xFEFF;'],
  ['numeric-next-line', '&#133;'],
  ['numeric-hair-space', '&#8202;'],
  ['numeric-line-separator', '&#8232;'],
  ['numeric-paragraph-separator', '&#8233;'],
  ['numeric-ideographic-space', '&#12288;'],
  ['numeric-zero-width-space', '&#8203;'],
  ['numeric-word-joiner', '&#8288;'],
  ['numeric-astral', '&#x1f9d1;&#x200d;&#x1f4bb;'],
  ['unknown-entity', '&notAnEntity;'],
  ['unterminated-entity', '&copy'],
] as const) {
  candidates.push(page(`entity-${name}`, `<p>${content}{value}</p>`));
}

// Real code points, rather than source escapes, exercise the raw JSX parser and
// printer. NEL and zero-width controls intentionally differ from String#trim.
for (const [name, content] of [
  ['bom', '\ufeff'],
  ['next-line', '\u0085'],
  ['mongolian-vowel-separator', '\u180e'],
  ['zero-width-space', '\u200b'],
  ['zero-width-non-joiner', '\u200c'],
  ['zero-width-joiner', '\u200d'],
  ['word-joiner', '\u2060'],
  ['left-to-right-mark', '\u200e'],
  ['narrow-no-break-space', '\u202f'],
  ['medium-mathematical-space', '\u205f'],
  ['ideographic-space', '\u3000'],
  ['line-separator', '\u2028'],
  ['paragraph-separator', '\u2029'],
  ['vertical-tab', '\u000b'],
  ['form-feed', '\u000c'],
] as const) {
  candidates.push(page(`unicode-${name}-text`, `<p>${content}{value}</p>`));
  candidates.push(
    page(
      `unicode-${name}-attribute`,
      `<Card children="${content}" footer={<span>Footer {value}</span>} />`
    )
  );
}

candidates.push(
  example(
    'bom-directive-prologue',
    '\ufeff"use client";\nexport const Page = () => <p>Hello {value}</p>;'
  ),
  example(
    'crlf-text-boundaries',
    'export const Page = () => <div>\r\n  First\r\n  <b>{value}</b>\r\n  Last\r\n</div>;\r\n'
  ),
  example(
    'cr-text-boundaries',
    'export const Page = () => <div>\r  First\r  <b>{value}</b>\r  Last\r</div>;\r'
  ),
  example(
    'crlf-only-array-and-comments',
    'export const Page = () => <div>\r\n{/* before */}\r\n{["First", value, <b key="tail">Tail {other}</b>]}\r\n{/* after */}\r\n</div>;'
  ),
  example(
    'cr-only-array-and-comments',
    'export const Page = () => <div>\r{/* before */}\r{["First", value, <b key="tail">Tail {other}</b>]}\r{/* after */}\r</div>;'
  ),
  page(
    'crlf-quoted-children',
    '<Card children="First\r\n    second\r\n  third" />'
  ),
  page('cr-quoted-children', '<Card children="First\r    second\r  third" />'),
  page(
    'newline-nel-quoted-children',
    '<Card children="First\n\u0085second" />'
  ),
  page(
    'newline-bom-quoted-children',
    '<Card children="First\n\ufeffsecond" />'
  ),
  page(
    'newline-nbsp-quoted-children',
    '<Card children="First\n\u00a0second" />'
  ),
  page('tab-quoted-children', '<Card children="First\tsecond" />'),
  page(
    'multiline-opaque-attribute',
    '<Branch branch={mode} a="First\r\n   second" b="\ufeff">Fallback {value}</Branch>',
    'import { Branch } from "gt-next";'
  ),
  page('comment-only', '<main>{/* one */}{/* two */}</main>'),
  page(
    'comment-between-text-and-expression',
    '<p>Before{/* keep boundary */}{value}{/* keep boundary */}after</p>'
  ),
  page(
    'comment-between-text-chunks',
    '<p>Before{/* boundary between literal children */}after</p>'
  ),
  page(
    'line-comment-array',
    '<p>{// one expression, still an array\n["First", value, <b key="last">Last</b>]}</p>'
  ),
  page(
    'comment-between-nested-fragments',
    '<>{/* outer */}<>{/* inner */}{value}</>{/* tail */}</>'
  ),
  page(
    'key-before-spread-call-order',
    '<Card key={recordKey()} {...loadProps()} title={<h2>Heading {value}</h2>}>Body {value}</Card>'
  ),
  page(
    'key-after-spread-call-order',
    '<Card {...loadProps()} key={recordKey()} title={<h2>Heading {value}</h2>}>Body {value}</Card>'
  ),
  page(
    'key-between-two-spreads',
    '<Card {...firstProps()} key={recordKey()} {...lastProps()}>Body {value}</Card>'
  ),
  page(
    'key-before-and-after-spread',
    '<Card key={firstKey()} {...loadProps()} key={lastKey()}>Body {value}</Card>'
  ),
  page(
    'void-key-side-effect',
    '<Card key={void recordKey()}>Body {value}</Card>'
  ),
  page(
    'void-key-side-effect-and-spread',
    '<main>Before <Card key={void recordKey()} {...loadProps()}>Body {value}</Card> after</main>'
  ),
  page(
    'spread-then-void-key-side-effect',
    '<main>Before <Card {...loadProps()} key={void recordKey()}>Body {value}</Card> after</main>'
  ),
  page('literal-void-key', '<Card key={void 0}>Body {value}</Card>'),
  page(
    'children-before-effectful-spread',
    '<Card children={<p>First {readValue()}</p>} {...loadProps()} />'
  ),
  page(
    'children-after-effectful-spread',
    '<Card {...loadProps()} children={<p>Last {readValue()}</p>} />'
  ),
  page(
    'children-between-effectful-spreads',
    '<Card {...firstProps()} children={<p>Middle {readValue()}</p>} {...lastProps()} />'
  ),
  page(
    'duplicate-explicit-children',
    '<Card children={<p>First {first()}</p>} children={<p>Second {second()}</p>} />'
  ),
  page(
    'duplicate-text-children',
    '<Card children="First" children="Second" />'
  ),
  page(
    'duplicate-children-with-spread',
    '<Card children={first()} {...loadProps()} children={<p>Last {last()}</p>} />'
  ),
  page(
    'duplicate-children-and-markup',
    '<Card children={<p>First {first()}</p>} children={<p>Second {second()}</p>}>Third {third()}</Card>'
  ),
  page(
    'shorthand-children-with-markup',
    '<Card children>Visible markup {value}</Card>'
  ),
  page(
    'shorthand-children-with-nested-markup',
    '<Card children><p>Nested markup {value}</p></Card>'
  ),
  page(
    'shorthand-then-explicit-children',
    '<Card children children={<p>Explicit {value}</p>} />'
  ),
  page(
    'explicit-then-shorthand-children',
    '<Card children={<p>Explicit {value}</p>} children />'
  ),
  page(
    'shorthand-opaque-content',
    '<Branch branch={mode} a b c={false}>Fallback {value}</Branch>',
    'import { Branch } from "gt-next";'
  ),
  page(
    'duplicate-opaque-content-props',
    '<Branch branch={mode} a={<p>First {first()}</p>} a={<p>Second {second()}</p>} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-computed-children',
    '<Card {...{ ["children"]: <p>Computed {value}</p>, children: <b>Explicit {other}</b> }} />'
  ),
  page(
    'spread-object-children-getter',
    '<Card {...{ get children() { return <p>Getter {value}</p>; }, title: <h2>Title {other}</h2> }}>Body {third}</Card>'
  ),
  page(
    'spread-object-child-function',
    '<Card {...{ children: () => <p>Callback {value}</p> }} />'
  ),
  page('spread-object-shorthand-children', '<Card {...{ children }} />'),
  page(
    'spread-object-string-children',
    '<Card {...{ "children": <p>Quoted key {value}</p> }} />'
  ),
  page(
    'spread-object-computed-static-children',
    '<Card {...{ ["children"]: "Computed text" }} />'
  ),
  page(
    'spread-object-computed-variable-children',
    '<Card {...{ [property]: <p>Computed {value}</p> }}>Actual {other}</Card>'
  ),
  page(
    'spread-object-first-children-property',
    '<Card {...{ children: <p>First {first()}</p>, children: <p>Second {second()}</p> }} />'
  ),
  page(
    'spread-object-children-and-outer-children',
    '<Card {...{ children: <p>First {first()}</p> }} children={<p>Second {second()}</p>}>Third {third()}</Card>'
  ),
  page(
    'spread-object-child-method',
    '<Card {...{ children() { return <p>Method {value}</p>; } }} />'
  ),
  page(
    'spread-object-child-async-method',
    '<Card {...{ async children() { return <p>Method {await loadValue()}</p>; } }} />'
  ),
  page(
    'spread-object-child-setter',
    '<Card {...{ set children(value) { record(<p>Setter {value}</p>); } }} />'
  ),
  page(
    'spread-object-child-getter-and-setter',
    '<Card {...{ get children() { return <p>Getter {value}</p>; }, set children(next) { record(<p>Setter {next}</p>); } }} />'
  ),
  page(
    'spread-object-method-and-body',
    '<Card {...{ label() { return <p>Method {value}</p>; }, title: <b>Heading {other}</b> }}>Body {third}</Card>'
  ),
  page(
    'spread-object-proto-literal',
    '<Card {...{ __proto__: prototype, children: <p>Child {value}</p> }} />'
  ),
  page(
    'spread-object-proto-quoted',
    '<Card {...{ "__proto__": prototype, children: <p>Child {value}</p> }} />'
  ),
  page(
    'spread-object-proto-computed',
    '<Card {...{ ["__proto__"]: prototype, children: <p>Child {value}</p> }} />'
  ),
  page(
    'spread-object-proto-shorthand',
    '<Card {...{ __proto__, children: <p>Child {value}</p> }} />'
  ),
  page(
    'spread-object-nested-spread',
    '<Card {...{ ...firstProps(), children: <p>Middle {value}</p>, ...lastProps() }} />'
  ),
  page(
    'spread-object-side-effect-property-order',
    '<Card {...{ first: first(), children: <p>Child {value()}</p>, last: last() }} />'
  ),
  page(
    'spread-object-opaque-control-and-content',
    '<Branch {...{ branch: mode, a: <b>Alpha {value}</b>, b: other, children: "Fallback" }} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-opaque-string-keys',
    '<Branch {...{ "branch": mode, "a": <b>Alpha {value}</b>, "data-value": other, "children": fallback }} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-opaque-computed-control',
    '<Branch {...{ ["branch"]: mode, ["a"]: <b>Alpha {value}</b>, ["children"]: fallback }} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-opaque-content-getter',
    '<Branch {...{ branch: mode, get a() { return <b>Getter {value}</b>; }, children: "Fallback" }} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-opaque-proto',
    '<Branch {...{ __proto__: prototype, branch: mode, a: <b>Alpha {value}</b> }} />',
    'import { Branch } from "gt-next";'
  ),
  page(
    'spread-object-manual-var-boundary',
    '<Var {...{ children: <Card title={<b>Opaque heading {value}</b>}>Opaque body {other}</Card> }} />',
    'import { Var } from "gt-next";'
  ),
  page(
    'spread-object-manual-t-boundary',
    '<T {...{ children: <Card title={<b>Independent heading {value}</b>}>Manual body {other}</Card> }} />',
    'import { T } from "gt-next";'
  ),
  page(
    'spread-object-key-before-spread',
    '<Card {...{ key: recordKey(), children: <p>Object {value}</p> }} {...loadProps()}>Markup {other}</Card>'
  ),
  page(
    'spread-object-key-after-spread',
    '<Card {...loadProps()} {...{ key: recordKey(), children: <p>Object {value}</p> }}>Markup {other}</Card>'
  ),
  example(
    'late-named-import',
    'export const Page = () => <main><T>Manual {value}</T><p>Automatic {other}</p></main>;\nimport { T } from "gt-next";'
  ),
  example(
    'late-opaque-import',
    'export function Page() { return <main><Choice branch={mode} a={<b>First {value}</b>} other={other} /></main>; }\nimport { Branch as Choice } from "gt-next";'
  ),
  example(
    'late-string-named-import',
    'export function Page() { return <Choice branch={mode} a={<b>First {value}</b>} other={other} />; }\nimport { "Branch" as Choice } from "gt-next";'
  ),
  example(
    'late-user-var-import',
    'export const Page = () => <p>Before <Data>{() => <span>Opaque {value}</span>}</Data> after {other}</p>;\nimport { "Var" as Data } from "gt-next";'
  ),
  page(
    'namespace-member-shadow-in-parameter',
    '<main><GT.T>Namespace {value}</GT.T>{((GT) => <GT.Var>Local namespace {value}</GT.Var>)(components)}</main>',
    'import * as GT from "gt-next";'
  ),
  example(
    'namespace-member-lexical-block',
    'import * as GT from "gt-next";\nexport function Page() { const outer = <GT.T>Outer {value}</GT.T>; { const GT = local; return <main>{outer}<GT.T>Inner {value}</GT.T></main>; } }'
  ),
  page(
    'member-spelling-from-local-object',
    '<main><Components.T>Local T {value}</Components.T><Components.GtInternalTranslateJsx>Local helper {other}</Components.GtInternalTranslateJsx></main>',
    'const Components = localComponents;'
  ),
  example(
    'catch-object-destructure-shadow',
    'import { T } from "gt-next";\nexport function Page() { try { return <T>Manual {value}</T>; } catch ({ component: T }) { return <T>Shadowed {value}<b>Nested {other}</b></T>; } }'
  ),
  example(
    'catch-array-destructure-shadow',
    'import { Var } from "gt-next";\nexport function Page() { try { return <p>Before <Var>{value}</Var></p>; } catch ([Var]) { return <Var>Shadowed {value}<b>Nested {other}</b></Var>; } }'
  ),
  example(
    'nested-destructured-parameter-shadow',
    'import { Branch as Choice } from "gt-next";\nexport function Inner({ slots: { Choice } }) { return <Choice branch={mode} a={<b>Local {value}</b>}>Body {other}</Choice>; }\nexport const Page = () => <Choice branch={mode} a={<b>Imported {value}</b>}>Fallback</Choice>;'
  ),
  example(
    'parameter-default-import-reference',
    'import { T } from "gt-next";\nexport function Page(T = <T>Initializer {value}</T>) { return <main><T>Parameter {value}</T></main>; }'
  ),
  example(
    'for-of-binding-shadow',
    'import { T } from "gt-next";\nexport function Page() { const rows = []; for (const T of components) { rows.push(<T>Local row {value}</T>); } return <main><T>Imported footer {value}</T>{rows}</main>; }'
  ),
  example(
    'for-destructured-binding-shadow',
    'import { Var } from "gt-next";\nexport function Page() { const rows = []; for (const { renderer: Var } of components) { rows.push(<Var>Local row {value}<span>Nested {other}</span></Var>); } return <main><Var>{value}</Var>{rows}</main>; }'
  ),
  example(
    'switch-lexical-binding-shadow',
    'import { Branch } from "gt-next";\nexport function Page() { switch (mode) { case "local": { const Branch = Local; return <Branch branch={mode} a={<b>Local {value}</b>}>Body {other}</Branch>; } default: return <Branch branch={mode} a={<b>Imported {value}</b>}>Fallback</Branch>; } }'
  ),
  example(
    'class-expression-name-shadow',
    'import { T } from "gt-next";\nexport const View = class T { render() { return <T>Class binding {value}</T>; } };\nexport const Page = () => <T>Imported {value}</T>;'
  ),
  example(
    'block-var-hoisting-shadow',
    'import { T } from "gt-next";\nexport function Inner() { const before = <T>Before declaration {value}</T>; if (condition) { var T = Local; } return <main>{before}<T>After declaration {value}</T></main>; }\nexport const Page = () => <T>Imported {value}</T>;'
  ),
  example(
    'type-only-import-and-local-value',
    'import type { T } from "gt-next";\nconst T = Local;\nexport const Page = () => <T>Local value {value}</T>;'
  ),
  example(
    'type-only-specifier-and-local-value',
    'import { type Var, T } from "gt-next";\nconst Var = Local;\nexport const Page = () => <main><Var>Local value {value}</Var><T>Manual {other}</T></main>;'
  ),
  page(
    'existing-translate-alias-only',
    '<Auto>Existing {value}<b>Descendant {other}</b></Auto>',
    'import { GtInternalTranslateJsx as Auto } from "gt-next";'
  ),
  page(
    'existing-variable-alias-only',
    '<AutoVar><p>Descendant {value}</p></AutoVar>',
    'import { GtInternalVar as AutoVar } from "gt-next";'
  ),
  page(
    'existing-string-helper-import',
    '<Auto>Existing {value}</Auto>',
    'import { "GtInternalTranslateJsx" as Auto } from "gt-next";'
  ),
  page(
    'existing-string-helper-import-with-new-content',
    '<main><Auto>Existing {value}</Auto><p>New {other}</p></main>',
    'import { "GtInternalTranslateJsx" as Auto } from "gt-next";'
  ),
  page(
    'existing-helpers-no-new-translation',
    '<main><Auto>{value}</Auto><AutoVar>{other}</AutoVar></main>',
    'import { GtInternalTranslateJsx as Auto, GtInternalVar as AutoVar } from "gt-next";'
  ),
  page(
    'existing-helper-alias-with-new-translation',
    '<main><Auto>Existing {value}</Auto><p>New {other}</p></main>',
    'import { GtInternalTranslateJsx as Auto } from "gt-next";'
  ),
  page(
    'existing-variable-alias-with-new-translation',
    '<p>New {value}<AutoVar>{other}</AutoVar></p>',
    'import { GtInternalVar as AutoVar } from "gt-next";'
  ),
  page(
    'existing-helpers-from-other-gt-source',
    '<main><Auto>Existing {value}</Auto><p>New {other}</p></main>',
    'import { GtInternalTranslateJsx as Auto, GtInternalVar as AutoVar } from "gt-react";'
  ),
  example(
    'existing-helper-parameter-shadow',
    'import { GtInternalTranslateJsx as Auto } from "gt-next";\nexport function Inner(Auto) { return <Auto>Local component {value}</Auto>; }\nexport const Page = () => <Auto>Existing {other}</Auto>;'
  ),
  example(
    'existing-helper-late-import',
    'export const Page = () => <main><Auto>Existing {value}</Auto><p>New {other}</p></main>;\nimport { GtInternalTranslateJsx as Auto } from "gt-next";'
  ),
  example(
    'jsx-filename-user-binding',
    'const _jsxFileName = computeFilename();\nexport const Page = () => <p>File {_jsxFileName}</p>;'
  ),
  example(
    'jsx-filename-numbered-user-binding',
    'const _jsxFileName2 = <b>File name {name}</b>;\nexport const Page = () => <p>File {_jsxFileName2}</p>;'
  ),
  example(
    'canonical-jsx-user-binding',
    'const $jsx = renderSomething;\nexport const Page = () => <p>Before {$jsx(value)} after</p>;'
  ),
  example(
    'canonical-helper-user-binding',
    'const $GtInternalTranslateJsx = localValue;\nexport const Page = () => <p>Value {$GtInternalTranslateJsx}</p>;'
  )
);

/**
 * Safety counts are handwritten from the rules and count all JSX elements bound
 * to imported automatic GT helpers, including wrappers already in the source.
 * Local components with the same spelling do not count. Every automatic helper
 * reference must resolve to an import. Existing-wrapper descendants retain the
 * compiler's traversal behavior, which does not guarantee idempotence.
 */
export interface SafetyExample extends Example {
  reason: string;
  expectedTranslateCount: number;
  expectedVariableCount: number;
  boundReferences: true;
}

const aliasReason =
  'The compiler detects an existing translation helper import but injects unaliased helper references without importing those local names.';
const lateImportReason =
  'The compiler visits JSX before its runtime import in this module and emits unbound jsx calls; the development transform can expose this even when production succeeds.';
const collisionReason =
  'The compiler imports and references its fixed helper names without avoiding existing module or function bindings.';

const safetyCandidates: Record<
  string,
  { reason: string; translate: number; variable: number }
> = {
  'adversarial/late-named-import': {
    reason: lateImportReason,
    translate: 1,
    variable: 1,
  },
  'adversarial/late-opaque-import': {
    reason: lateImportReason,
    translate: 1,
    variable: 2,
  },
  'adversarial/late-string-named-import': {
    reason: lateImportReason,
    translate: 1,
    variable: 2,
  },
  'adversarial/late-user-var-import': {
    reason: lateImportReason,
    translate: 1,
    variable: 1,
  },
  'adversarial/existing-translate-alias-only': {
    reason: aliasReason,
    translate: 2,
    variable: 1,
  },
  'adversarial/existing-helper-alias-with-new-translation': {
    reason: aliasReason,
    translate: 2,
    variable: 1,
  },
  'adversarial/existing-helpers-from-other-gt-source': {
    reason: aliasReason,
    translate: 2,
    variable: 1,
  },
  'adversarial/existing-helper-parameter-shadow': {
    reason: aliasReason,
    translate: 2,
    variable: 1,
  },
  'adversarial/existing-helper-late-import': {
    reason: aliasReason,
    translate: 2,
    variable: 1,
  },
};

function safety(
  source: Example,
  translate: number,
  variable: number,
  reason: string
): SafetyExample {
  return {
    ...source,
    reason,
    expectedTranslateCount: translate,
    expectedVariableCount: variable,
    boundReferences: true,
  };
}

// These explicit cases remain covered by native binding/count
// checks. Invalid compiler references are never normalized into valid output.
export const safetyExamples: SafetyExample[] = [
  ...candidates.flatMap((source) => {
    const expected = safetyCandidates[source.name];
    return expected
      ? [safety(source, expected.translate, expected.variable, expected.reason)]
      : [];
  }),
  safety(
    example(
      'safety-top-level-translate-name',
      'const GtInternalTranslateJsx = Local;\nexport const Page = () => <div>Hello {value}<GtInternalTranslateJsx>Local {other}</GtInternalTranslateJsx></div>;'
    ),
    1,
    2,
    collisionReason
  ),
  safety(
    example(
      'safety-top-level-variable-name',
      'const GtInternalVar = Local;\nexport const Page = () => <div>Hello {value}<GtInternalVar>Local {other}</GtInternalVar></div>;'
    ),
    1,
    2,
    collisionReason
  ),
  safety(
    example(
      'safety-parameter-translate-name',
      'export function Page(GtInternalTranslateJsx) { return <div>Hello {value}<GtInternalTranslateJsx>Local {other}</GtInternalTranslateJsx></div>; }'
    ),
    1,
    2,
    collisionReason
  ),
  safety(
    example(
      'safety-parameter-variable-name',
      'export function Page(GtInternalVar) { return <div>Hello {value}<GtInternalVar>Local {other}</GtInternalVar></div>; }'
    ),
    1,
    2,
    collisionReason
  ),
  safety(
    example(
      'safety-existing-unaliased-translate',
      'import { GtInternalTranslateJsx } from "gt-next";\nexport const Page = () => <main><GtInternalTranslateJsx>Existing {value}</GtInternalTranslateJsx><p>New {other}</p></main>;'
    ),
    2,
    1,
    aliasReason
  ),
];

export const examples: Example[] = candidates.filter(
  ({ name }) => !Object.hasOwn(safetyCandidates, name)
);

examples.push(
  page(
    'lowercase-translation-alias-is-intrinsic',
    '<t>Hello {value}<span>Nested {other}</span></t>',
    'import { T as t } from "gt-next";'
  ),
  page(
    'lowercase-variable-alias-is-intrinsic',
    '<v>Hello {value}{show && <span>Nested {other}</span>}</v>',
    'import { Var as v } from "gt-next";'
  ),
  page(
    'lowercase-opaque-alias-is-intrinsic',
    '<branch branch={mode} a={<b>Alpha {value}</b>}>{other}</branch>',
    'import { Branch as branch } from "gt-next";'
  ),
  page(
    'uppercase-translation-alias-is-component',
    '<Translate>Hello {value}<span>Nested {other}</span></Translate>',
    'import { T as Translate } from "gt-next";'
  ),
  page(
    'unicode-translation-alias-is-component',
    '<é>Hello {value}<span>Nested {other}</span></é>',
    'import { T as é } from "gt-next";'
  ),
  page(
    'unicode-variable-alias-is-component',
    '<α>Hello {value}{show && <span>Nested {other}</span>}</α>',
    'import { Var as α } from "gt-next";'
  ),
  page(
    'unicode-opaque-alias-is-component',
    '<β branch={mode} a={<b>Alpha {value}</b>}>{other}</β>',
    'import { Branch as β } from "gt-next";'
  ),
  page(
    'hyphenated-intrinsic-component-spelling',
    '<gt-t>Hello {value}<gt-var>{show && <span>Nested {other}</span>}</gt-var></gt-t>',
    'import { T as gt_t, Var as gt_var } from "gt-next";'
  ),
  page(
    'lowercase-namespace-object-member',
    '<gt.T>Hello {value}<span>Nested {other}</span></gt.T>',
    'import * as gt from "gt-next";'
  ),
  example(
    'existing-both-unaliased-helpers',
    'import { GtInternalTranslateJsx, GtInternalVar } from "gt-next";\nexport const Page = () => <main><GtInternalTranslateJsx>Existing <GtInternalVar>{value}</GtInternalVar></GtInternalTranslateJsx><p>New {other}</p></main>;'
  )
);
