import fs from 'node:fs';
import path from 'node:path';
import { logger } from '../console/logger.js';
import chalk from 'chalk';
import { DEFAULT_TRANSLATIONS_DIR } from '../utils/constants.js';

function toRelativeImportPath(relativePath: string) {
  const normalizedPath = relativePath.split(path.sep).join(path.posix.sep);

  if (!normalizedPath) {
    return './';
  }

  // Dynamic imports must use explicit relative specifiers; values like
  // "src/_gt" are otherwise treated as package names by Vite and Node.
  const hasExplicitRelativePrefix =
    normalizedPath === '..' ||
    normalizedPath.startsWith('../') ||
    normalizedPath.startsWith('./');

  return hasExplicitRelativePrefix
    ? `${normalizedPath}/`
    : `./${normalizedPath}/`;
}

function getLoaderContent(translationsDir: string, publicPath: string) {
  return `
export default async function loadTranslations(locale) {
  try {
    // Load translations from ${translationsDir} directory
    // This matches the GT config files.gt.output path
    const t = await import(\`${publicPath}\${locale}.json\`);
    return t.default;
  } catch (error) {
    console.warn(\`Failed to load translations for locale \${locale}:\`, error);
    return {};
  }
}
`;
}

// The same template with its two variable parts matched, so any loader this
// CLI generated (the template has not changed) is recognized and updatable.
const GENERATED_LOADER = new RegExp(
  `^${getLoaderContent('\0', '\0')
    .replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    .replaceAll('\0', '[^\\n`]*')}$`
);

export type LoadTranslationsFileResult =
  | 'created'
  | 'updated'
  | 'unchanged'
  | 'custom';

/**
 * Creates or updates the generated loadTranslations.js for translationsDir
 * (relative to appDirectory) and its empty locale stubs. A loader that was
 * not generated by the CLI is left untouched and reported as 'custom'.
 * Directory and stub failures propagate.
 */
export async function createLoadTranslationsFile(
  appDirectory: string,
  translationsDir: string = DEFAULT_TRANSLATIONS_DIR,
  locales: string[]
): Promise<LoadTranslationsFileResult> {
  const usingSrcDirectory = fs.existsSync(path.join(appDirectory, 'src'));

  const loadTranslationsDir = usingSrcDirectory
    ? path.join(appDirectory, 'src')
    : appDirectory;
  const translationsPath = path.resolve(appDirectory, translationsDir);
  const publicPath = toRelativeImportPath(
    path.relative(loadTranslationsDir, translationsPath)
  );
  const filePath = path.join(loadTranslationsDir, 'loadTranslations.js');
  const content = getLoaderContent(translationsDir, publicPath);

  const existing = fs.existsSync(filePath)
    ? await fs.promises.readFile(filePath, 'utf8')
    : undefined;
  if (existing === content) return 'unchanged';
  if (existing !== undefined && !GENERATED_LOADER.test(existing)) {
    logger.info(
      `Found a custom ${chalk.cyan('loadTranslations.js')} at ${chalk.cyan(
        filePath
      )}; leaving it unchanged.`
    );
    return 'custom';
  }

  // Stubs first, so a directory failure leaves no loader pointing at it.
  await fs.promises.mkdir(translationsPath, { recursive: true });
  for (const locale of locales) {
    const stubPath = path.join(translationsPath, `${locale}.json`);
    if (!fs.existsSync(stubPath)) await fs.promises.writeFile(stubPath, '{}');
  }
  await fs.promises.writeFile(filePath, content);
  logger.info(
    `${existing === undefined ? 'Created' : 'Updated'} ${chalk.cyan(
      'loadTranslations.js'
    )} at ${chalk.cyan(filePath)}.`
  );
  return existing === undefined ? 'created' : 'updated';
}
