# Multi-platform build aliases
[alias]
# WASM builds (original SWC plugin targets)
build-plugin = "build --target wasm32-wasip1 --release"
build-plugin-dev = "build --target wasm32-wasip1"

# Native platform builds
build-linux-x64 = "build --target x86_64-unknown-linux-gnu --release"
build-linux-arm64 = "build --target aarch64-unknown-linux-gnu --release"
build-android-x64 = "build --target x86_64-linux-android --release"
build-android-arm64 = "build --target aarch64-linux-android --release"
build-darwin-x64 = "build --target x86_64-apple-darwin --release"
build-darwin-arm64 = "build --target aarch64-apple-darwin --release"
build-win32-x64 = "build --target x86_64-pc-windows-msvc --release"
build-win32-arm64 = "build --target aarch64-pc-windows-msvc --release"
