import ClientProvider from './react-context/provider/ClientProvider';
import LocaleSelector from './react-context/ui/LocaleSelector';
import RegionSelector from './react-context/ui/RegionSelector';

import {
  T,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useRegion,
  GTProvider,
  Var,
  Num,
  Currency,
  DateTime,
  Static,
  Derive,
  Plural,
  Branch,
  useLocales,
  useLocaleSelector,
  useSetLocale,
  useGTClass,
  useLocaleProperties,
  useRegionSelector,
  useLocaleDirection,
  useVersionId,
  useMessages,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  derive,
  declareVar,
  decodeVars,
  mFallback,
  gtFallback,
} from '@generaltranslation/react-core';

export {
  GTProvider,
  ClientProvider,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useLocales,
  useSetLocale,
  useLocaleSelector,
  useRegion,
  useRegionSelector,
  useGTClass,
  useLocaleProperties,
  useLocaleDirection,
  useVersionId,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  derive,
  declareVar,
  decodeVars,
  useMessages,
  mFallback,
  gtFallback,
  T,
  Var,
  Num,
  DateTime,
  Currency,
  Static,
  Derive,
  Branch,
  Plural,
  LocaleSelector,
  RegionSelector,
};
