import ClientProvider from './provider/ClientProvider';
import LocaleSelector from './ui/LocaleSelector';
import RegionSelector from './ui/RegionSelector';

import {
  T,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useRegion,
  GTProvider,
  Var,
  Num,
  Currency,
  DateTime,
  Static,
  Plural,
  Branch,
  useLocales,
  useLocaleSelector,
  useSetLocale,
  useGTClass,
  useLocaleProperties,
  useRegionSelector,
  useLocaleDirection,
  useMessages,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  declareVar,
  decodeVars,
  mFallback,
  gtFallback,
} from '@generaltranslation/react-core';

export {
  GTProvider,
  ClientProvider,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useLocales,
  useSetLocale,
  useLocaleSelector,
  useRegion,
  useRegionSelector,
  useGTClass,
  useLocaleProperties,
  useLocaleDirection,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  declareVar,
  decodeVars,
  useMessages,
  mFallback,
  gtFallback,
  T,
  Var,
  Num,
  DateTime,
  Currency,
  Static,
  Branch,
  Plural,
  LocaleSelector,
  RegionSelector,
};
