// React Server Component context surface.

export { GTProvider, LocaleSelector } from '#context-server';

export {
  Branch,
  Currency,
  createRenderPipeline,
  createRenderVariable,
  DateTime,
  Derive,
  getFormatLocales,
  getPluralBranch,
  getReactI18nCache,
  getReadonlyConditionStoreWithFallback,
  getShouldTranslate,
  getTranslationsSnapshot,
  GtInternalBranch,
  GtInternalCurrency,
  GtInternalDateTime,
  GtInternalDerive,
  GtInternalNum,
  GtInternalPlural,
  GtInternalRelativeTime,
  GtInternalVar,
  Num,
  Plural,
  prepareT,
  RelativeTime,
  renderDefaultChildren,
  renderPreparedT,
  renderTranslatedChildren,
  renderVariable,
  setReactI18nCache,
  T,
  t,
  Var,
} from '@generaltranslation/react-core/components-rsc';

export {
  decodeMsg,
  decodeOptions,
  decodeVars,
  declareVar,
  derive,
  gtFallback,
  mFallback,
  msg,
} from '@generaltranslation/react-core/pure';

export type {
  CurrencyProps,
  DateTimeProps,
  JsxTranslationOptions,
  NumProps,
  PluralProps,
  PreparedT,
  RelativeTimeFormatOptions,
  RelativeTimeProps,
  RenderVariable,
  ResolvedCurrencyProps,
  ResolvedDateTimeProps,
  ResolvedNumProps,
  ResolvedPluralProps,
  ResolvedRelativeTimeProps,
} from '@generaltranslation/react-core/components-rsc';
