import { GTProvider } from './react-context/provider/GTProvider';
import LocaleSelector from './react-context/ui/LocaleSelector';
import RegionSelector from './react-context/ui/RegionSelector';

import {
  T,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useRegion,
  Var,
  Num,
  Currency,
  DateTime,
  Static,
  Plural,
  Branch,
  useLocales,
  useLocaleSelector,
  useSetLocale,
  useGTClass,
  useLocaleProperties,
  useRegionSelector,
  useLocaleDirection,
  useMessages,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  declareVar,
  decodeVars,
  mFallback,
  gtFallback,
} from '@generaltranslation/react-core';
import {
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
} from '@generaltranslation/react-core/types';

export {
  Var,
  Num,
  Currency,
  DateTime,
  Static,
  T,
  GTProvider,
  Plural,
  Branch,
  useGT,
  useTranslations,
  useDefaultLocale,
  useLocale,
  useLocales,
  useSetLocale,
  useLocaleSelector,
  useRegion,
  useRegionSelector,
  useGTClass,
  useLocaleProperties,
  useLocaleDirection,
  LocaleSelector,
  RegionSelector,
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
  msg,
  decodeMsg,
  decodeOptions,
  declareStatic,
  declareVar,
  decodeVars,
  useMessages,
  mFallback,
  gtFallback,
  t,
};
