// No useContext related exports should go through here!

import {
  addGTIdentifier,
  writeChildrenAsObjects,
  isVariableObject,
  flattenDictionary,
  getDictionaryEntry,
  isValidDictionaryEntry,
  getVariableProps,
  getPluralBranch,
  getEntryAndMetadata,
  getVariableName,
  renderDefaultChildren,
  renderTranslatedChildren,
  renderSkeleton,
  getDefaultRenderSettings,
  defaultLocaleCookieName,
  defaultRegionCookieName,
  mergeDictionaries,
  reactHasUse,
  getSubtree,
  getSubtreeWithCreation,
  injectEntry,
  isDictionaryEntry,
  stripMetadataFromEntries,
  injectHashes,
  injectTranslations,
  injectFallbacks,
  injectAndMerge,
  collectUntranslatedEntries,
  msg,
  decodeMsg,
  decodeOptions,
} from '@generaltranslation/react-core/internal';

import {
  MFunctionType,
  TFunctionType,
  Dictionary,
  RenderMethod,
  TranslatedChildren,
  Translations,
  RenderVariable,
  VariableProps,
  DictionaryEntry,
  FlattenedDictionary,
  Metadata,
  Entry,
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
  LocalesDictionary,
  DictionaryContent,
  DictionaryObject,
  CustomLoader,
  _Message,
  _Messages,
  GTContextType,
  GTProp,
} from '@generaltranslation/react-core/types';

import { ClientProviderProps } from './types/config';

// Type exports
export type {
  RenderMethod,
  Dictionary,
  DictionaryEntry,
  FlattenedDictionary,
  Metadata,
  GTProp,
  Entry,
  TranslatedChildren,
  Translations,
  GTContextType,
  ClientProviderProps,
  DictionaryTranslationOptions,
  InlineTranslationOptions,
  RuntimeTranslationOptions,
  DictionaryContent,
  DictionaryObject,
  LocalesDictionary,
  CustomLoader,
  RenderVariable,
  VariableProps,
  MFunctionType,
  TFunctionType,
  _Message,
  _Messages,
};

// Constant exports
export {
  getDefaultRenderSettings,
  defaultLocaleCookieName,
  defaultRegionCookieName,
  reactHasUse,
  msg,
  decodeMsg,
  decodeOptions,
};

// Function exports
export {
  addGTIdentifier,
  writeChildrenAsObjects,
  isVariableObject,
  flattenDictionary,
  getDictionaryEntry,
  isValidDictionaryEntry,
  getVariableProps,
  getPluralBranch,
  getEntryAndMetadata,
  getVariableName,
  renderDefaultChildren,
  renderTranslatedChildren,
  renderSkeleton,
  mergeDictionaries,
  getSubtree,
  getSubtreeWithCreation,
  injectEntry,
  isDictionaryEntry,
  stripMetadataFromEntries,
  injectHashes,
  injectTranslations,
  injectFallbacks,
  injectAndMerge,
  collectUntranslatedEntries,
};
