/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsrRouteImport } from './routes/ssr'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as DataOnlyRouteImport } from './routes/data-only'
import { Route as IndexRouteImport } from './routes/index'

const SsrRoute = SsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOnlyRoute = DataOnlyRouteImport.update({
  id: '/data-only',
  path: '/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-only': typeof DataOnlyRoute
  '/spa': typeof SpaRoute
  '/ssr': typeof SsrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-only': typeof DataOnlyRoute
  '/spa': typeof SpaRoute
  '/ssr': typeof SsrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-only': typeof DataOnlyRoute
  '/spa': typeof SpaRoute
  '/ssr': typeof SsrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-only' | '/spa' | '/ssr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-only' | '/spa' | '/ssr'
  id: '__root__' | '/' | '/data-only' | '/spa' | '/ssr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataOnlyRoute: typeof DataOnlyRoute
  SpaRoute: typeof SpaRoute
  SsrRoute: typeof SsrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssr': {
      id: '/ssr'
      path: '/ssr'
      fullPath: '/ssr'
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-only': {
      id: '/data-only'
      path: '/data-only'
      fullPath: '/data-only'
      preLoaderRoute: typeof DataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataOnlyRoute: DataOnlyRoute,
  SpaRoute: SpaRoute,
  SsrRoute: SsrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
