[package]
name = "gt-swc-plugin"
version = "0.1.0"
edition = "2021"

# Essential lints only
[lints.clippy]
# Catch common issues
unwrap_used = "warn"
expect_used = "warn"
todo = "warn"

[lib]
crate-type = ["cdylib"]

[profile.release]
# Optimize for plugin distribution (both native and WASM)
codegen-units = 1
lto = true
opt-level = "s"  # Optimize for size
strip = "symbols"  # Strip debug symbols

# Platform-specific configurations for cross-compilation
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

# Windows ARM64 uses MSVC (GNU toolchain not supported yet)

# Android NDK linkers
[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

# Android NDK environment (add to shell profile)
# export ANDROID_NDK_HOME="/opt/homebrew/share/android-ndk"  
# export PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-arm64/bin:$PATH"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_core = { version = "34.0.*", features = ["ecma_plugin_transform"] }
sha2 = "0.10"

# .cargo/config.toml defines few alias to build plugin.
# cargo build-wasip1 generates wasm32-wasip1 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
