# Rustfmt configuration for gt-swc-plugin
# https://rust-lang.github.io/rustfmt/

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Function and control flow formatting
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80
single_line_if_else_max_width = 50

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style preferences
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
format_code_in_doc_comments = false
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Preserve"
match_block_trailing_comma = false
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_try_shorthand = false
where_single_line = false
wrap_comments = false

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Unstable features (require nightly rustfmt)
# Uncomment if using nightly
# unstable_features = true
# format_strings = false
# skip_children = false