import { existsSync, readdirSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { hashSource } from 'generaltranslation/id';
import { describe, expect, it } from 'vitest';
import { captureRuntimeSeeds } from '../capture';

const repositoryRoot = resolve(import.meta.dirname, '../../../..');
const seedsRoot = resolve(repositoryRoot, 'tests/seeds');
const knownRuntimeDifference = resolve(
  seedsRoot,
  'complex-cases/more-extreme-edge-cases'
);
const corpusCases = collectSeedDirectories(seedsRoot)
  // The current runtime preserves an explicit empty Var name while this
  // legacy fixture substitutes an autogenerated key.
  .filter((directory) => directory !== knownRuntimeDifference)
  .map((directory) => [relative(seedsRoot, directory), directory] as const);

describe('React runtime seed corpus', () => {
  it.each(corpusCases)(
    'matches the stored runtime oracle for %s',
    async (_name, seedDirectory) => {
      const expected = JSON.parse(
        await readFile(resolve(seedDirectory, 'expected.json'), 'utf8')
      );
      const candidate = await captureRuntimeSeeds({
        cwd: repositoryRoot,
        file: resolve(seedDirectory, 'page.tsx'),
      });

      expect(candidate.seeds).toHaveLength(1);
      const [seed] = candidate.seeds;
      const expectedByHash = getExpectedByHash(expected);
      const expectedTree = expectedByHash?.[seed.hash] ?? expected;
      expect(expectedTree).toBeDefined();
      expect(normalizeSemanticWire(seed.jsxChildren)).toEqual(
        normalizeSemanticWire(expectedTree)
      );
      if (!expectedByHash) {
        expect(seed.hash).toBe(
          hashSource({
            source: expectedTree,
            dataFormat: 'JSX',
            ...seed.metadata,
          })
        );
      }
    }
  );
});

function getExpectedByHash(
  expected: unknown
): Record<string, unknown> | undefined {
  if (!isRecord(expected)) return;
  if (expected.static === true && isRecord(expected.content)) {
    return expected.content;
  }
  const keys = Object.keys(expected);
  if (keys.length > 0 && keys.every((key) => /^[a-f0-9]{16}$/.test(key))) {
    return expected;
  }
}

function collectSeedDirectories(directory: string): string[] {
  if (
    existsSync(resolve(directory, 'page.tsx')) &&
    existsSync(resolve(directory, 'expected.json'))
  ) {
    return [directory];
  }
  return readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => collectSeedDirectories(resolve(directory, entry.name)));
}

function normalizeSemanticWire(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeSemanticWire);
  if (!isRecord(value)) return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== 't' || !('i' in value) || 'k' in value)
      .map(([key, child]) => [key, normalizeSemanticWire(child)])
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
