export const EXCLUDED_DIRS = [
  './node_modules',
  './.git',
  './.locadex',
  './.next',
  './dist',
  './build',
  './out',
  './public',
  './static',
  './next.config.js',
  './next.config.ts',
  './next.config.mjs',
  './next.config.cjs',
  './next.config.mts',
  './next.config.cts',
];
