import fs from 'node:fs';
import path from 'node:path';
import { createDiagnosticMessage } from 'generaltranslation/internal';

const GENERATED_ENTRY_MARKER = '// Generated by gt setup for Vite SPAs.';
const MODULE_EXTENSIONS = new Set([
  '.js',
  '.jsx',
  '.mjs',
  '.mts',
  '.ts',
  '.tsx',
]);

type ModuleScript = {
  src: string;
  importSuffix: string;
  srcStart: number;
  srcEnd: number;
  filePath: string;
};

function toModuleSpecifier(fromDirectory: string, filePath: string): string {
  const relativePath = path
    .relative(fromDirectory, filePath)
    .split(path.sep)
    .join(path.posix.sep);

  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function getAttribute(tag: string, name: string) {
  const match = new RegExp(
    `\\b${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`,
    'i'
  ).exec(tag);
  if (!match) return null;

  const value = match[1] ?? match[2] ?? match[3] ?? '';
  const valueOffset = match[0].lastIndexOf(value);
  return {
    value,
    start: match.index + valueOffset,
    end: match.index + valueOffset + value.length,
  };
}

function resolveBrowserModulePath(
  appDirectory: string,
  htmlDirectory: string,
  src: string
): string | null {
  if (/^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(src)) return null;

  const pathname = src.split(/[?#]/, 1)[0];
  if (!pathname) return null;

  const filePath = path.resolve(
    src.startsWith('/') ? appDirectory : htmlDirectory,
    pathname.replace(/^\//, '')
  );
  const relativeToApp = path.relative(appDirectory, filePath);
  if (relativeToApp.startsWith('..') || path.isAbsolute(relativeToApp)) {
    return null;
  }
  if (!MODULE_EXTENSIONS.has(path.extname(filePath))) return null;
  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) return null;

  return filePath;
}

function findModuleScripts(
  html: string,
  appDirectory: string,
  indexHtmlPath: string
): ModuleScript[] {
  const scripts: ModuleScript[] = [];
  const htmlDirectory = path.dirname(indexHtmlPath);
  const scriptPattern = /<script\b[^>]*>/gi;

  for (const match of html.matchAll(scriptPattern)) {
    const tagStart = match.index ?? 0;
    const lastCommentStart = html.lastIndexOf('<!--', tagStart);
    const lastCommentEnd = html.lastIndexOf('-->', tagStart);
    if (lastCommentStart > lastCommentEnd) continue;

    const tag = match[0];
    const type = getAttribute(tag, 'type');
    const src = getAttribute(tag, 'src');
    if (type?.value.toLowerCase() !== 'module' || !src?.value) continue;

    const filePath = resolveBrowserModulePath(
      appDirectory,
      htmlDirectory,
      src.value
    );
    if (!filePath) continue;

    scripts.push({
      src: src.value,
      importSuffix: src.value.match(/[?#].*$/)?.[0] ?? '',
      srcStart: tagStart + src.start,
      srcEnd: tagStart + src.end,
      filePath,
    });
  }

  return scripts;
}

function getBrowserSrc(
  originalSrc: string,
  appDirectory: string,
  indexHtmlPath: string,
  entryPath: string
): string {
  const relativeToApp = path
    .relative(appDirectory, entryPath)
    .split(path.sep)
    .join(path.posix.sep);
  const relativeToHtml = path
    .relative(path.dirname(indexHtmlPath), entryPath)
    .split(path.sep)
    .join(path.posix.sep);

  if (originalSrc.startsWith('/')) return `/${relativeToApp}`;
  if (originalSrc.startsWith('./')) return `./${relativeToHtml}`;
  return relativeToHtml;
}

function createEntryContent({
  entryPath,
  originalEntryPath,
  originalEntrySuffix,
  configFilepath,
  loadTranslationsPath,
}: {
  entryPath: string;
  originalEntryPath: string;
  originalEntrySuffix: string;
  configFilepath: string;
  loadTranslationsPath: string;
}): string {
  const entryDirectory = path.dirname(entryPath);
  const configImport = toModuleSpecifier(entryDirectory, configFilepath);
  const loaderImport = toModuleSpecifier(
    entryDirectory,
    loadTranslationsPath
  ).replace(/\.[cm]?[jt]sx?$/, '');
  const appImport = `${toModuleSpecifier(
    entryDirectory,
    originalEntryPath
  )}${originalEntrySuffix}`;

  return `${GENERATED_ENTRY_MARKER}
import { initializeGTSPA } from 'gt-react';
import gtConfig from '${configImport}';
import loadTranslations from '${loaderImport}';

await initializeGTSPA({
  ...gtConfig,
  projectId: import.meta.env.VITE_GT_PROJECT_ID,
  devApiKey: import.meta.env.VITE_GT_DEV_API_KEY,
  loadTranslations,
});

await import('${appImport}');
`;
}

function createSetupWarning(whatHappened: string, details?: string): string {
  return createDiagnosticMessage({
    whatHappened,
    fix: 'Call initializeGTSPA in a separate entry module, dynamically import the existing app entry after initialization, and point the module script in index.html to the new entry',
    details,
    docsUrl: 'https://generaltranslation.com/docs/react/react-spa-quickstart',
  });
}

function chooseEntryPath(
  originalEntryPath: string,
  extension: '.js' | '.ts',
  contentForPath: (entryPath: string) => string
): { entryPath: string; content: string } | null {
  const entryDirectory = path.dirname(originalEntryPath);
  const candidates = [
    path.join(entryDirectory, `index${extension}`),
    path.join(entryDirectory, `gt-entry${extension}`),
  ];

  for (const entryPath of candidates) {
    const content = contentForPath(entryPath);
    if (!fs.existsSync(entryPath)) return { entryPath, content };

    const existingContent = fs.readFileSync(entryPath, 'utf8');
    if (existingContent === content) return { entryPath, content };
  }

  return null;
}

export async function setupViteSpaRuntime({
  appDirectory,
  configFilepath,
  filesUpdated,
  warnings,
}: {
  appDirectory: string;
  configFilepath: string;
  filesUpdated: string[];
  warnings: string[];
}): Promise<void> {
  const indexHtmlPath = path.join(appDirectory, 'index.html');
  if (!fs.existsSync(indexHtmlPath)) {
    warnings.push(
      createSetupWarning(
        'GT could not initialize the Vite SPA automatically because no index.html file was found',
        indexHtmlPath
      )
    );
    return;
  }

  const html = await fs.promises.readFile(indexHtmlPath, 'utf8');
  const moduleScripts = findModuleScripts(html, appDirectory, indexHtmlPath);
  const generatedScript = moduleScripts.find((script) =>
    fs.readFileSync(script.filePath, 'utf8').includes(GENERATED_ENTRY_MARKER)
  );
  if (generatedScript) return;

  if (moduleScripts.length !== 1) {
    warnings.push(
      createSetupWarning(
        moduleScripts.length === 0
          ? 'GT could not initialize the Vite SPA automatically because index.html does not reference a local module entry'
          : 'GT could not initialize the Vite SPA automatically because index.html references multiple local module entries',
        indexHtmlPath
      )
    );
    return;
  }

  const originalScript = moduleScripts[0];
  const originalExtension = path.extname(originalScript.filePath);
  const entryExtension: '.js' | '.ts' = /\.[cm]?tsx?$/.test(originalExtension)
    ? '.ts'
    : '.js';
  const loadTranslationsPath = path.join(
    fs.existsSync(path.join(appDirectory, 'src'))
      ? path.join(appDirectory, 'src')
      : appDirectory,
    'loadTranslations.js'
  );
  const absoluteConfigPath = path.resolve(appDirectory, configFilepath);
  const entry = chooseEntryPath(
    originalScript.filePath,
    entryExtension,
    (entryPath) =>
      createEntryContent({
        entryPath,
        originalEntryPath: originalScript.filePath,
        originalEntrySuffix: originalScript.importSuffix,
        configFilepath: absoluteConfigPath,
        loadTranslationsPath,
      })
  );

  if (!entry) {
    warnings.push(
      createSetupWarning(
        'GT could not create a Vite SPA initialization entry without overwriting an existing file',
        path.dirname(originalScript.filePath)
      )
    );
    return;
  }

  if (!fs.existsSync(entry.entryPath)) {
    await fs.promises.writeFile(entry.entryPath, entry.content, 'utf8');
    filesUpdated.push(entry.entryPath);
  }

  const browserSrc = getBrowserSrc(
    originalScript.src,
    appDirectory,
    indexHtmlPath,
    entry.entryPath
  );
  const updatedHtml =
    html.slice(0, originalScript.srcStart) +
    browserSrc +
    html.slice(originalScript.srcEnd);
  if (updatedHtml !== html) {
    await fs.promises.writeFile(indexHtmlPath, updatedHtml, 'utf8');
    filesUpdated.push(indexHtmlPath);
  }
}
