import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/**
 * Source map v3 attribution. Each generated byte of an emitted JS file is
 * charged to the original source that the nearest preceding mapping segment
 * on the same line points to. Bytes before the first segment of a line, and
 * segments without a source, are reported with a `null` source.
 */

interface RawSourceMap {
  version: number;
  sources?: (string | null)[];
  sourceRoot?: string;
  mappings?: string;
  sections?: { offset: { line: number; column: number }; map: RawSourceMap }[];
}

/** One mapping segment: generated position plus an index into `sources`. */
interface Segment {
  line: number;
  column: number;
  source: number;
}

interface FlatMap {
  sources: string[];
  /** Segments grouped by generated line, each group sorted by column. */
  lines: Map<number, Segment[]>;
}

const BASE64 =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const BASE64_VALUES = new Int8Array(128).fill(-1);
for (let i = 0; i < BASE64.length; i++) BASE64_VALUES[BASE64.charCodeAt(i)] = i;

/** Decodes the `mappings` field into per-line segments (VLQ, delta encoded). */
export function decodeMappings(
  mappings: string
): { line: number; column: number; source: number | null }[] {
  const result: { line: number; column: number; source: number | null }[] = [];
  let line = 0;
  let column = 0;
  let source = 0;
  let index = 0;
  const fields: number[] = [];

  while (index < mappings.length) {
    const char = mappings.charCodeAt(index);
    if (char === 59 /* ; */) {
      line++;
      column = 0;
      index++;
      continue;
    }
    if (char === 44 /* , */) {
      index++;
      continue;
    }

    fields.length = 0;
    while (index < mappings.length) {
      const c = mappings.charCodeAt(index);
      if (c === 44 || c === 59) break;
      let value = 0;
      let shift = 0;
      let digit: number;
      do {
        digit = BASE64_VALUES[mappings.charCodeAt(index++)] ?? -1;
        if (digit < 0) throw new Error('Invalid VLQ character in mappings');
        value += (digit & 31) << shift;
        shift += 5;
      } while (digit & 32);
      fields.push(value & 1 ? -(value >>> 1) : value >>> 1);
    }

    column += fields[0] ?? 0;
    if (fields.length >= 4) {
      source += fields[1]!;
      result.push({ line, column, source });
    } else {
      result.push({ line, column, source: null });
    }
  }
  return result;
}

/** Flattens a regular or indexed (sectioned) source map. */
function flatten(
  map: RawSourceMap,
  mapDir: string,
  projectRoot?: string
): FlatMap {
  const sources: string[] = [];
  const sourceIndex = new Map<string, number>();
  const lines = new Map<number, Segment[]>();

  const visit = (
    part: RawSourceMap,
    lineOffset: number,
    columnOffset: number
  ) => {
    if (part.sections) {
      for (const section of part.sections) {
        visit(
          section.map,
          lineOffset + section.offset.line,
          section.offset.line === 0
            ? columnOffset + section.offset.column
            : section.offset.column
        );
      }
      return;
    }
    const local = (part.sources ?? []).map((name) => {
      const key = resolveSource(
        name ?? '',
        part.sourceRoot,
        mapDir,
        projectRoot
      );
      let id = sourceIndex.get(key);
      if (id === undefined) {
        id = sources.length;
        sources.push(key);
        sourceIndex.set(key, id);
      }
      return id;
    });
    for (const segment of decodeMappings(part.mappings ?? '')) {
      const line = segment.line + lineOffset;
      const column = segment.column + (segment.line === 0 ? columnOffset : 0);
      const source =
        segment.source === null ? -1 : (local[segment.source] ?? -1);
      let group = lines.get(line);
      if (!group) lines.set(line, (group = []));
      group.push({ line, column, source });
    }
  };

  visit(map, 0, 0);
  for (const group of lines.values()) group.sort((a, b) => a.column - b.column);
  return { sources, lines };
}

/**
 * Turns a `sources` entry into an absolute path when it is a relative path or
 * a file URL. Bundler-specific schemes (turbopack://, webpack://) and virtual
 * module ids are returned without the scheme so they can be classified.
 */
export function resolveSource(
  source: string,
  sourceRoot: string | undefined,
  mapDir: string,
  projectRoot?: string
): string {
  if (source.startsWith('file://')) return new URL(source).pathname;
  const scheme = /^[a-z][a-z0-9+.-]*:\/\/\/?/i.exec(source);
  const path = scheme ? source.slice(scheme[0].length) : source;
  // Turbopack writes sources relative to its root as [project]/...
  if (path.startsWith('[project]/') && projectRoot) {
    return resolve(projectRoot, safeDecode(path.slice('[project]/'.length)));
  }
  if (scheme || path.startsWith('\0')) return path;
  return resolve(mapDir, sourceRoot ?? '', safeDecode(path));
}

function safeDecode(path: string): string {
  try {
    return decodeURIComponent(path);
  } catch {
    return path;
  }
}

/** Finds and parses the source map for an emitted JS file, if it has one. */
export function loadSourceMap(
  file: string,
  code: string
): { map: RawSourceMap; dir: string } | null {
  const match = /\/\/[#@]\s*sourceMappingURL=([^\s'"]+)\s*$/.exec(
    code.slice(-2048)
  );
  const url = match?.[1];
  if (url?.startsWith('data:')) {
    const comma = url.indexOf(',');
    const payload = url.slice(comma + 1);
    const text = url.slice(0, comma).endsWith(';base64')
      ? Buffer.from(payload, 'base64').toString('utf8')
      : decodeURIComponent(payload);
    return { map: JSON.parse(text), dir: dirname(file) };
  }
  const candidates = url ? [resolve(dirname(file), url)] : [];
  candidates.push(`${file}.map`);
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return {
        map: JSON.parse(readFileSync(candidate, 'utf8')),
        dir: dirname(candidate),
      };
    }
  }
  return null;
}

const ASCII = /^[\x00-\x7f]*$/;

export type { RawSourceMap };

/**
 * Attributes every byte of `code` to an original source path. The returned
 * map's keys are absolute source paths (or virtual ids); `null` collects bytes
 * that no mapping covers. The values sum to the UTF-8 byte length of `code`.
 */
export function attributeBytes(
  code: string,
  map: RawSourceMap,
  mapDir: string,
  projectRoot?: string
): Map<string | null, number> {
  const { sources, lines } = flatten(map, mapDir, projectRoot);
  const totals = new Map<string | null, number>();
  const add = (key: string | null, bytes: number) => {
    if (bytes > 0) totals.set(key, (totals.get(key) ?? 0) + bytes);
  };

  let lineStart = 0;
  let lineNumber = 0;
  while (lineStart <= code.length) {
    let lineEnd = code.indexOf('\n', lineStart);
    const hasNewline = lineEnd !== -1;
    if (!hasNewline) lineEnd = code.length;
    const text = code.slice(lineStart, lineEnd);
    const ascii = ASCII.test(text);
    const byteLength = (from: number, to: number) =>
      ascii ? to - from : Buffer.byteLength(text.slice(from, to));

    const segments = lines.get(lineNumber) ?? [];
    let cursor = 0;
    let owner: string | null = null;
    for (const segment of segments) {
      const column = Math.min(segment.column, text.length);
      if (column > cursor) add(owner, byteLength(cursor, column));
      if (column >= cursor) cursor = column;
      owner = segment.source >= 0 ? (sources[segment.source] ?? null) : null;
    }
    // The rest of the line and its newline belong to the last segment.
    add(owner, byteLength(cursor, text.length) + (hasNewline ? 1 : 0));

    if (!hasNewline) break;
    lineStart = lineEnd + 1;
    lineNumber++;
  }

  // Bundlers emit few or no segments for modules converted from data, such as
  // JSON translation files. A map with one source owns the whole file.
  const unmapped = totals.get(null);
  if (sources.length === 1 && unmapped) {
    totals.delete(null);
    add(sources[0]!, unmapped);
  }
  return totals;
}
