name: Upload Assets to R2

on:
  push:

jobs:
  upload-assets:
    name: Upload Assets to Cloudflare R2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS CLI for R2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload assets to R2
        run: |
          aws s3 sync assets/ s3://${{ secrets.R2_BUCKET_NAME }}/ \
            --endpoint-url ${{ secrets.R2_ENDPOINT_URL }} \
            --delete \
            --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
