name: Upload Assets to R2

on:
  push:

jobs:
  upload-assets:
    name: Upload Assets to Cloudflare R2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Upload assets to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: r2 object put assets --directory=assets --recursive
