name: Upload Assets to R2

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
  workflow_dispatch:

jobs:
  upload-assets:
    name: Upload Assets to Cloudflare R2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: ryand56/r2-upload-action@b801a390acbdeb034c5e684ff5e1361c06639e7c # v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ vars.R2_ASSETS_BUCKET_NAME }}
          source-dir: assets
          destination-dir: ./
